services:
  postgres_db:
    restart: unless-stopped
    image: pgvector:latest
    volumes:
      - postgres_db_summary:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=summarization
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test1234
    # env_file:
    #   - .env
    ports:
      - "5432:5432"

  # faq_generator_backend:
  #   restart: unless-stopped
  #   image: faq-generator-backend:v1

  #   env_file:
  #     - .env_backend.docker

  #   # env_file:
  #   #   - .env
  #   ports:
  #     - "8000:8000"

volumes:
  postgres_db_summary:
